BoxLayout:
    orientation: "vertical"
    BoxLayout:
        TextInput:
            id: input_number
            font_size: 48
            multiline: False
        BoxLayout:
            orientation: "vertical"
            Button:
                text: "Up"
            Button:
                text: "Down"
    Button:
        text: "Convert miles to km"
    Label:
        text: "Enter miles click convert button"